source\python\py-start.rst:19: [broken] https://scipy.org/: HTTPSConnectionPool(host='scipy.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
utils.rst:5: [local] irc://freenode.net
utils.rst:5: [broken] http://github.com/example/crawler/issues: 404 Client Error: Not Found for url: https://github.com/example/crawler/issues
